/* Generated By:JavaCC: Do not edit this line. RPLanguageConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RPLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTERA = 9;
  /** RegularExpression Id. */
  int CIFRA = 10;
  /** RegularExpression Id. */
  int PARAPERTA_Q = 11;
  /** RegularExpression Id. */
  int PARCHIUSA_Q = 12;
  /** RegularExpression Id. */
  int PV = 13;
  /** RegularExpression Id. */
  int EPS = 14;
  /** RegularExpression Id. */
  int PIPE = 15;
  /** RegularExpression Id. */
  int PUO_ESSERE = 16;
  /** RegularExpression Id. */
  int LOOK_A_HEAD = 17;
  /** RegularExpression Id. */
  int NON_TERM = 18;
  /** RegularExpression Id. */
  int TERM = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENTO = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<LETTERA>",
    "<CIFRA>",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"eps\"",
    "\"|\"",
    "\"::=\"",
    "<LOOK_A_HEAD>",
    "<NON_TERM>",
    "<TERM>",
  };

}
