/* Generated By:JavaCC: Do not edit this line. RPLanguageConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RPLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int L = 9;
  /** RegularExpression Id. */
  int N = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int EPS = 12;
  /** RegularExpression Id. */
  int PIPE = 13;
  /** RegularExpression Id. */
  int PUO_ESSERE = 14;
  /** RegularExpression Id. */
  int OPZ_NON_TERM = 15;
  /** RegularExpression Id. */
  int NON_TERM = 16;
  /** RegularExpression Id. */
  int OPZ_TERM = 17;
  /** RegularExpression Id. */
  int TERM = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENTO = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<L>",
    "<N>",
    "\";\"",
    "\"eps\"",
    "\"|\"",
    "<PUO_ESSERE>",
    "<OPZ_NON_TERM>",
    "<NON_TERM>",
    "<OPZ_TERM>",
    "<TERM>",
  };

}
