/* Generated By:JavaCC: Do not edit this line. RPLanguage.java */
import java.io.*;
import java.util.*;
import my_package.*;

public class RPLanguage implements RPLanguageConstants {
        public static void main(String args []) throws ParseException, FileNotFoundException
        {
        RPLanguage parser = new RPLanguage(new FileInputStream(new File("input/regole1.txt")));

                //parsing e costruzione dell'albero sintattico
                Node root=parser.start();
                Btree tree=new Btree(root);
                Visitor visitor=new Visitor();

//		//visita preorder dell'albero sinattico//		System.out.println("\nPRE-ORDER VISIT:\n");//		ArrayList <Node> nodeList = visitor.preorderVisit(tree);//		Iterator<Node> itr1=nodeList.iterator();//		while(itr1.hasNext())//    		System.out.println((itr1.next()).getVal()+"\n");////		//visita postorder dell'albero sintattico//		System.out.println("\nPOST-ORDER VISIT:\n");//		nodeList = visitor.postorderVisit(tree);//		itr1=nodeList.iterator();//		while(itr1.hasNext())//			System.out.println((itr1.next()).getVal()+"\n");

                //generazione del codice per javaCC
                System.out.println("\u005cn\u005cnJavaCC-code:\u005cn");
                GenJavaCCCode generator = new GenJavaCCCode();
                ArrayList<String> code=generator.genCode(tree);
                Iterator<String> itr2=code.iterator();
                while(itr2.hasNext())
                        System.out.println(itr2.next());
        }

/*----------------------------------------------------------------------------------------REGOLE DI PRODUZIONE*/
  final public Node start() throws ParseException {
 Node start_nptr, grammatica_nptr;
    System.out.println("<start> ::= <grammatica>;");
    grammatica_nptr = grammatica();
    jj_consume_token(0);
    start_nptr=grammatica_nptr;
    {if (true) return start_nptr;}
    throw new Error("Missing return statement in function");
  }

//<grammatica> ::= <regole>;
  final public Node grammatica() throws ParseException {
 Node grammatica_nptr, regole_nptr;
   System.out.println("<grammatica> ::= <regole>;");
    regole_nptr = regole();
    grammatica_nptr=regole_nptr;
    {if (true) return grammatica_nptr;}
    throw new Error("Missing return statement in function");
  }

//<regole> ::= <regola> <regola_queue>;
  final public Node regole() throws ParseException {
 Node regole_nptr, regola_nptr, regola_queue_nptr;
   System.out.println("<regole> ::= <regola> <regola_queue>;");
    regola_nptr = regola();
    regola_queue_nptr = regola_queue(regola_nptr);
    regole_nptr=regola_queue_nptr;
    {if (true) return regole_nptr;}
    throw new Error("Missing return statement in function");
  }

//<regola_queue> ::= <regole> | eps;
  final public Node regola_queue(Node regola_nptr_inherited) throws ParseException {
 Node regola_queue_nptr, regole_nptr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_LOOKAHEAD:
    case NON_TERM:
   System.out.println("<regola_queue> ::= <regole>;");
      regole_nptr = regole();
   regola_queue_nptr=new Node(Symbol.REGOLE, "regole", regola_nptr_inherited, regole_nptr);
   {if (true) return regola_queue_nptr;}
      break;
    default:
      jj_la1[0] = jj_gen;
   System.out.println("<regola_queue> ::= eps;");

    regola_queue_nptr=regola_nptr_inherited;
    {if (true) return regola_queue_nptr;}
    }
    throw new Error("Missing return statement in function");
  }

//<regola> ::= [OP_LOOKAHEAD PARAPERTA_T NUM_LOOKAHEAD PARCHIUSA_T] NON_TERM PUO_ESSERE <corpo> PV;
  final public Node regola() throws ParseException {
 Node regola_nptr, corpo_nptr;
 Token OP_LOOKAHEAD_t, NUM_LOOKAHEAD_t, NON_TERM_t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_LOOKAHEAD:
   System.out.println("<regola> ::= OP_LOOKAHEAD PARAPERTA_T NUM_LOOKAHEAD PARCHIUSA_T NON_TERM PUO_ESSERE <corpo> PV;");
      OP_LOOKAHEAD_t = jj_consume_token(OP_LOOKAHEAD);
      jj_consume_token(PARAPERTA_T);
      NUM_LOOKAHEAD_t = jj_consume_token(NUM_LOOKAHEAD);
      jj_consume_token(PARCHIUSA_T);
      NON_TERM_t = jj_consume_token(NON_TERM);
      jj_consume_token(PUO_ESSERE);
      corpo_nptr = corpo();
      jj_consume_token(PV);
    regola_nptr=new Node(Symbol.REGOLA_LLK, "regola_llk", new Node(Symbol.NUM_LOOKAHEAD, NUM_LOOKAHEAD_t.image), new Node(Symbol.NON_TERM, NON_TERM_t.image), corpo_nptr);
    {if (true) return regola_nptr;}
      break;
    case NON_TERM:
   System.out.println("<regola> ::= NON_TERM PUO_ESSERE <corpo> PV;");
      NON_TERM_t = jj_consume_token(NON_TERM);
      jj_consume_token(PUO_ESSERE);
      corpo_nptr = corpo();
      jj_consume_token(PV);
    regola_nptr=new Node(Symbol.REGOLA_LL1, "regola_ll1", new Node(Symbol.NON_TERM, NON_TERM_t.image), corpo_nptr);
    {if (true) return regola_nptr;}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//<corpo> ::= <elementi> <elementi_queue>;
  final public Node corpo() throws ParseException {
 Node corpo_nptr, elementi_nptr, elementi_queue_nptr;
   System.out.println("<corpo> ::=  <elementi> <elementi_queue>;");
    elementi_nptr = elementi();
    elementi_queue_nptr = elementi_queue(elementi_nptr);
    elementi_nptr=elementi_queue_nptr;
    {if (true) return elementi_nptr;}
    throw new Error("Missing return statement in function");
  }

//<elementi_queue> ::= PIPE <corpo> | eps;
  final public Node elementi_queue(Node elementi_nptr_inherited) throws ParseException {
 Node elementi_queue_nptr, corpo_nptr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PIPE:
   System.out.println("<elementi_queue> ::=  PIPE <corpo>;");
      jj_consume_token(PIPE);
      corpo_nptr = corpo();
    elementi_queue_nptr=new Node(Symbol.OPPURE, "oppure", elementi_nptr_inherited, corpo_nptr);
    {if (true) return elementi_queue_nptr;}
      break;
    default:
      jj_la1[2] = jj_gen;
   System.out.println("<elementi_queue> ::= eps;");

    elementi_queue_nptr=elementi_nptr_inherited;
    {if (true) return elementi_queue_nptr;}
    }
    throw new Error("Missing return statement in function");
  }

//<elementi> ::= <elemento> <elemento_queue>;
  final public Node elementi() throws ParseException {
 Node elementi_nptr, elemento_nptr, elemento_queue_nptr;
   System.out.println("<elementi> ::=  <elemento> <elemento_queue>;");
    elemento_nptr = elemento();
    elemento_queue_nptr = elemento_queue(elemento_nptr);
    elementi_nptr=elemento_queue_nptr;
    {if (true) return elementi_nptr;}
    throw new Error("Missing return statement in function");
  }

//<elemento_queue> ::= <elementi> | eps;
  final public Node elemento_queue(Node elemento_nptr_inherited) throws ParseException {
 Node elemento_queue_nptr, elementi_nptr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PARAPERTA_Q:
    case EPS:
    case NON_TERM:
    case TERM:
   System.out.println("<elemento_queue> ::= <elementi>;");
      elementi_nptr = elementi();
    elemento_queue_nptr=new Node(Symbol.CONCAT, "concat", elemento_nptr_inherited, elementi_nptr);
    {if (true) return elemento_queue_nptr;}
      break;
    default:
      jj_la1[3] = jj_gen;
   System.out.println("<elemento_queue> ::=  eps;");

    elemento_queue_nptr=elemento_nptr_inherited;
    {if (true) return elemento_queue_nptr;}
    }
    throw new Error("Missing return statement in function");
  }

//<elemento> ::= TERM | NON_TERM | eps | PARAPERTA_Q <elementi> PARCHIUSA_Q;
  final public Node elemento() throws ParseException {
 Node elemento_nptr, elementi_nptr;
 Token TERM_t, NON_TERM_t, EPS_t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TERM:
   System.out.println("<elemento> ::=  TERM;");
      TERM_t = jj_consume_token(TERM);
    elemento_nptr=new Node(Symbol.TERM, TERM_t.image);
    {if (true) return elemento_nptr;}
      break;
    case NON_TERM:
   System.out.println("<elemento> ::=  NON_TERM;");
      NON_TERM_t = jj_consume_token(NON_TERM);
    elemento_nptr=new Node(Symbol.NON_TERM, NON_TERM_t.image);
    {if (true) return elemento_nptr;}
      break;
    case EPS:
   System.out.println("<elemento> ::=  EPS;");
      EPS_t = jj_consume_token(EPS);
    elemento_nptr=new Node(Symbol.EPS, EPS_t.image);
    {if (true) return elemento_nptr;}
      break;
    case PARAPERTA_Q:
   System.out.println("<elemento> ::= PARAPERTA_Q <elementi> PARCHIUSA_Q;");
      jj_consume_token(PARAPERTA_Q);
      elementi_nptr = elementi();
      jj_consume_token(PARCHIUSA_Q);
    elemento_nptr=new Node(Symbol.OPZ, "?", elementi_nptr);
    {if (true) return elemento_nptr;}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public RPLanguageTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x300000,0x300000,0x20000,0x612000,0x612000,};
   }

  /** Constructor with InputStream. */
  public RPLanguage(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RPLanguage(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RPLanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public RPLanguage(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RPLanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public RPLanguage(RPLanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RPLanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[23];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 23; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
